version: '3'

services:
  severance-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - severance-data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/severance.db
    restart: unless-stopped
    networks:
      - app-network

  tailscale:
    image: tailscale/tailscale:latest
    volumes:
      - ./tailscale-data:/var/lib/tailscale
    environment:
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - TS_SERVE_PORT=3000
      - TS_SERVE_CONFIG=tcp://severance-app:3000
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
